### ISSUE TITLE
Multiple captcha not working on single page

### ISSUE THREAD

**Issue by amitbindal09** [haruncpi/laravel-simple-captcha#1]
Hi,

I have two different form in my page and I am trying to use captcha with different name but it is not working.

I checked the code and found the issue, it is storing question and answer value in same session key for all the captcha that'w why it is not working.

We can make it working by passing dynamic session key like input name but I don't know how to pass dynamic as I am new to Laravel.

Please help for the same.

Thanks
Amit Bindal

**Comment by haruncpi** [comment]
Please make a PR with a sophisticated solution.
